This is METAFONT, Version 2.7182818 (TeX Live 2017) (preloaded base=mf 2017.5.23)  9 MAR 2018 10:46
**fizzbuzz.py prep/games/
(fizzbuzz.py
>> import.unittest
! Isolated expression.
<to be read again> 
                   def
l.3 def
        fizz_buzz(n):
? ls
Type <return> to proceed, S to scroll future error messages,
R to run without stopping, Q to run quietly,
I to insert something, E to edit your file,
1 or ... or 9 to ignore the next 1 to 9 tokens of input,
H for help, X to quit.
? ^^[
Type <return> to proceed, S to scroll future error messages,
R to run without stopping, Q to run quietly,
I to insert something, E to edit your file,
1 or ... or 9 to ignore the next 1 to 9 tokens of input,
H for help, X to quit.
? R
OK, entering nonstopmode...
! Extra tokens will be flushed.
<to be read again> 
                   def
l.3 def
        fizz_buzz(n):
I've just read as much of that statement as I could fathom,
so a semicolon should have been next. It's very puzzling...
but I'll try to get myself back together, by ignoring
everything up to the next `;'. Please insert a semicolon
now in front of anything that you don't want me to delete.
(See Chapter 27 of The METAFONTbook for an example.)

)
! File ended while scanning to the end of the statement.
<inserted text> 
                ;
<*> fizzbuzz.py
                prep/games/
A previous error seems to have propagated,
causing me to read past where you wanted me to stop.
I'll try to recover; but if the error is serious,
you'd better type `E' or `X' now and fix your file.

>> prep
>> games
! Not implemented: (unknown numeric)/(unknown numeric).
<to be read again> 
                   /
<*> fizzbuzz.py prep/games/
                           
I'm afraid I don't know how to apply that operation to that
combination of types. Continue, and I'll return the second
argument (see above) as the result of the operation.

! Emergency stop.
<*> fizzbuzz.py prep/games/
                           
*** (job aborted, no legal end found)


